platform :ios, ‘8.0’
target "TangTradePlatform" do
use_frameworks!
pod 'AFNetworking', '~> 3.1.0’
pod 'ReactiveCocoa', '~> 2.5'
pod 'SDWebImage', '~> 4.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.1.0'
pod 'IQKeyboardManager', '~> 4.0.13'
pod 'SocketRocket'
end
